import { useState } from 'react'
import { createUserWithEmailAndPassword, GoogleAuthProvider, signInWithEmailAndPassword, signInWithPopup } from 'firebase/auth'
import { AlertCircle, Loader2, Lock, LogIn, Mail, UserPlus, X } from 'lucide-react'
import { auth } from '../services/firebase'

export default function AuthModal({ isOpen, onClose }) {
  const [isSignUp, setIsSignUp] = useState(false)
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [errorMsg, setErrorMsg] = useState('')
  if (!isOpen) return null
  const readableError = (error) => ({ 'auth/invalid-credential': 'Email hoặc mật khẩu không chính xác.', 'auth/email-already-in-use': 'Email này đã được sử dụng.', 'auth/weak-password': 'Mật khẩu cần tối thiểu 6 ký tự.', 'auth/invalid-email': 'Email không hợp lệ.', 'auth/popup-closed-by-user': 'Bạn đã đóng cửa sổ đăng nhập Google.' }[error.code] || 'Không thể đăng nhập. Vui lòng thử lại.')
  const handleSubmit = async (event) => { event.preventDefault(); setLoading(true); setErrorMsg(''); try { if (isSignUp) await createUserWithEmailAndPassword(auth, email, password); else await signInWithEmailAndPassword(auth, email, password); onClose() } catch (error) { setErrorMsg(readableError(error)) } finally { setLoading(false) } }
  const handleGoogleLogin = async () => { setLoading(true); setErrorMsg(''); try { await signInWithPopup(auth, new GoogleAuthProvider()); onClose() } catch (error) { setErrorMsg(readableError(error)) } finally { setLoading(false) } }
  return <div className="fixed inset-0 z-[999] flex items-center justify-center bg-black/40 p-4 backdrop-blur-sm"><div className="relative w-full max-w-md rounded-3xl border border-slate-100 bg-white p-7 shadow-2xl"><button onClick={onClose} className="absolute right-5 top-5 text-slate-400" aria-label="Đóng"><X size={20} /></button><div className="mb-6 text-center"><h2 className="text-2xl font-bold text-slate-800">{isSignUp ? 'Tạo tài khoản' : 'Chào mừng trở lại'}</h2><p className="mt-1 text-sm text-slate-500">{isSignUp ? 'Lưu tiến độ học tập trên mọi thiết bị' : 'Đăng nhập để tiếp tục lộ trình học'}</p></div>{errorMsg && <div className="mb-4 flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-600"><AlertCircle size={16} />{errorMsg}</div>}<form onSubmit={handleSubmit} className="space-y-3.5"><label className="block text-xs font-semibold text-slate-600">Email<div className="relative mt-1"><Mail className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="example@gmail.com" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-slate-800" /></div></label><label className="block text-xs font-semibold text-slate-600">Mật khẩu<div className="relative mt-1"><Lock className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input type="password" required value={password} onChange={(event) => setPassword(event.target.value)} placeholder="••••••••" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-slate-800" /></div></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-slate-900 py-3 text-sm font-medium text-white disabled:opacity-50">{loading ? <Loader2 className="animate-spin" size={18} /> : isSignUp ? <><UserPlus size={18} />Đăng ký</> : <><LogIn size={18} />Đăng nhập</>}</button></form><div className="my-5 text-center text-xs text-slate-400">hoặc</div><button onClick={handleGoogleLogin} disabled={loading} className="w-full rounded-xl border border-slate-200 py-2.5 text-sm font-medium text-slate-700 disabled:opacity-50">Tiếp tục với Google</button><p className="mt-5 text-center text-xs text-slate-500">{isSignUp ? 'Đã có tài khoản? ' : 'Chưa có tài khoản? '}<button onClick={() => { setIsSignUp((value) => !value); setErrorMsg('') }} className="font-semibold text-slate-900">{isSignUp ? 'Đăng nhập ngay' : 'Đăng ký miễn phí'}</button></p></div></div>
}
